/*
 *  This file is part of the WebKit open source project.
 *  This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public License
 *  along with this library; see the file COPYING.LIB.  If not, write to
 *  the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 *  Boston, MA 02110-1301, USA.
 */

#if !defined(__WEBKITDOM_H_INSIDE__) && !defined(BUILDING_WEBKIT)
#error "Only <webkitdom/webkitdom.h> can be included directly."
#endif

#ifndef WebKitDOMPerformanceNavigation_h
#define WebKitDOMPerformanceNavigation_h

#include <glib-object.h>
#include <webkitdom/WebKitDOMObject.h>
#include <webkitdom/webkitdomdefines.h>

G_BEGIN_DECLS

#define WEBKIT_TYPE_DOM_PERFORMANCE_NAVIGATION            (webkit_dom_performance_navigation_get_type())
#define WEBKIT_DOM_PERFORMANCE_NAVIGATION(obj)            (G_TYPE_CHECK_INSTANCE_CAST((obj), WEBKIT_TYPE_DOM_PERFORMANCE_NAVIGATION, WebKitDOMPerformanceNavigation))
#define WEBKIT_DOM_PERFORMANCE_NAVIGATION_CLASS(klass)    (G_TYPE_CHECK_CLASS_CAST((klass),  WEBKIT_TYPE_DOM_PERFORMANCE_NAVIGATION, WebKitDOMPerformanceNavigationClass)
#define WEBKIT_DOM_IS_PERFORMANCE_NAVIGATION(obj)         (G_TYPE_CHECK_INSTANCE_TYPE((obj), WEBKIT_TYPE_DOM_PERFORMANCE_NAVIGATION))
#define WEBKIT_DOM_IS_PERFORMANCE_NAVIGATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),  WEBKIT_TYPE_DOM_PERFORMANCE_NAVIGATION))
#define WEBKIT_DOM_PERFORMANCE_NAVIGATION_GET_CLASS(obj)  (G_TYPE_INSTANCE_GET_CLASS((obj),  WEBKIT_TYPE_DOM_PERFORMANCE_NAVIGATION, WebKitDOMPerformanceNavigationClass))

struct _WebKitDOMPerformanceNavigation {
    WebKitDOMObject parent_instance;
};

struct _WebKitDOMPerformanceNavigationClass {
    WebKitDOMObjectClass parent_class;
};

WEBKIT_API GType
webkit_dom_performance_navigation_get_type (void);

/**
 * webkit_dom_performance_navigation_get_redirect_count:
 * @self: A #WebKitDOMPerformanceNavigation
 *
 * Returns: A #gushort
**/
WEBKIT_API gushort
webkit_dom_performance_navigation_get_redirect_count(WebKitDOMPerformanceNavigation* self);

G_END_DECLS

#endif /* WebKitDOMPerformanceNavigation_h */
