/*
 *  This file is part of the WebKit open source project.
 *  This file has been generated by generate-bindings.pl. DO NOT MODIFY!
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public License
 *  along with this library; see the file COPYING.LIB.  If not, write to
 *  the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 *  Boston, MA 02110-1301, USA.
 */

#if !defined(__WEBKITDOM_H_INSIDE__) && !defined(BUILDING_WEBKIT)
#error "Only <webkitdom/webkitdom.h> can be included directly."
#endif

#ifndef WebKitDOMBatteryManager_h
#define WebKitDOMBatteryManager_h

#include <glib-object.h>
#include <webkitdom/WebKitDOMObject.h>
#include <webkitdom/webkitdomdefines.h>

G_BEGIN_DECLS

#define WEBKIT_TYPE_DOM_BATTERY_MANAGER            (webkit_dom_battery_manager_get_type())
#define WEBKIT_DOM_BATTERY_MANAGER(obj)            (G_TYPE_CHECK_INSTANCE_CAST((obj), WEBKIT_TYPE_DOM_BATTERY_MANAGER, WebKitDOMBatteryManager))
#define WEBKIT_DOM_BATTERY_MANAGER_CLASS(klass)    (G_TYPE_CHECK_CLASS_CAST((klass),  WEBKIT_TYPE_DOM_BATTERY_MANAGER, WebKitDOMBatteryManagerClass)
#define WEBKIT_DOM_IS_BATTERY_MANAGER(obj)         (G_TYPE_CHECK_INSTANCE_TYPE((obj), WEBKIT_TYPE_DOM_BATTERY_MANAGER))
#define WEBKIT_DOM_IS_BATTERY_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass),  WEBKIT_TYPE_DOM_BATTERY_MANAGER))
#define WEBKIT_DOM_BATTERY_MANAGER_GET_CLASS(obj)  (G_TYPE_INSTANCE_GET_CLASS((obj),  WEBKIT_TYPE_DOM_BATTERY_MANAGER, WebKitDOMBatteryManagerClass))

struct _WebKitDOMBatteryManager {
    WebKitDOMObject parent_instance;
};

struct _WebKitDOMBatteryManagerClass {
    WebKitDOMObjectClass parent_class;
};

WEBKIT_API GType
webkit_dom_battery_manager_get_type (void);

#if !defined(WEBKIT_DISABLE_DEPRECATED)
/**
 * webkit_dom_battery_manager_dispatch_event:
 * @self: A #WebKitDOMBatteryManager
 * @event: A #WebKitDOMEvent
 * @error: #GError
 *
 * Returns: A #gboolean
 *
 * Deprecated: 2.4: Use webkit_dom_event_target_dispatch_event() instead.
**/
WEBKIT_DEPRECATED_FOR(webkit_dom_event_target_dispatch_event) gboolean
webkit_dom_battery_manager_dispatch_event(WebKitDOMBatteryManager* self, WebKitDOMEvent* event, GError** error);
#endif /* WEBKIT_DISABLE_DEPRECATED */

/**
 * webkit_dom_battery_manager_get_charging:
 * @self: A #WebKitDOMBatteryManager
 *
 * Returns: A #gboolean
**/
WEBKIT_API gboolean
webkit_dom_battery_manager_get_charging(WebKitDOMBatteryManager* self);

/**
 * webkit_dom_battery_manager_get_charging_time:
 * @self: A #WebKitDOMBatteryManager
 *
 * Returns: A #gdouble
**/
WEBKIT_API gdouble
webkit_dom_battery_manager_get_charging_time(WebKitDOMBatteryManager* self);

/**
 * webkit_dom_battery_manager_get_discharging_time:
 * @self: A #WebKitDOMBatteryManager
 *
 * Returns: A #gdouble
**/
WEBKIT_API gdouble
webkit_dom_battery_manager_get_discharging_time(WebKitDOMBatteryManager* self);

/**
 * webkit_dom_battery_manager_get_level:
 * @self: A #WebKitDOMBatteryManager
 *
 * Returns: A #gdouble
**/
WEBKIT_API gdouble
webkit_dom_battery_manager_get_level(WebKitDOMBatteryManager* self);

G_END_DECLS

#endif /* WebKitDOMBatteryManager_h */
